react-component/form

README.md, examples/validateTrigger.js, src/createForm.jsx, src/utils.js
=> feat: add `validate` #5

src/createForm.jsx
之前增加 `option.validate` 时少改动了一个地方。。。
=> fix: should detect rules' existence with `hasRules`

examples/data-binding-form.js
Close: https://github.com/react-component/form/issues/11
=> fix the initial state of data-binding-form example #11

src/createBaseForm.jsx
=> fix: should support virtual field, close: #15

README.md
=> add formOption.withRef into README

src/createBaseForm.js
ref: https://github.com/react-component/form/issues/38#issuecomment-272356294
=> chore: add warning for invalid usage

.travis.yml, package.json, src/createDOMForm.js, tests/scroll.spec.js
close ant-design/ant-design#5184
=> scrollable container cannot be itself

src/createDOMForm.js
close ant-design/ant-design#6037
=> Fix scrollable node is not scrollable in some situations

src/utils.js, tests/form.spec.js
Close: https://github.com/ant-design/ant-design/issues/8386
=> fix: should return directly when set inexist field, close: ant-design/ant-design#8386

README.md, examples/across-router.js, examples/async-init.js, examples/dynamic-fields.js, examples/dynamic.js, examples/file-input.js, examples/getFieldDecorator.js, examples/input-array.js, examples/modal.js, examples/nested-field.js, examples/normalize.js, examples/overview.js, examples/parallel-form.js, examples/redux.js, examples/server-validate.js, examples/setFieldsValue.js, examples/start-end-date.js, examples/suggest.js, examples/validateFirst.js, examples/validateTrigger.js, package.json, src/index.js, src/propTypes.js
=> Add formShape for propTypes validation

src/createBaseForm.js, tests/getFieldProps.spec.js
Close: https://github.com/ant-design/ant-design/issues/8985
=> fix: should support disordered array as fieldname, close: ant-design/ant-design#8985

examples/form-create-component.js, package.json, src/createFormComponent.js, src/index.js, src/utils.js
Method of use:
```jsx
const Demo = () => (
<FormCreate {...options}>
{({ getFieldDecorator, ... }) => (
<Form>
{...}
</Form>
)}
<FormCreate/>
)
```
=> feat: add FormCreate component 

examples/form-create-component.js, src/FormScope.js
https://github.com/react-component/form/issues/192
=> 修复FormScope示例中的resetAll无效

examples/promise-validate.js, src/createBaseForm.js, tests/async-validation.spec.js
原来的pr https://github.com/react-component/form/pull/187
=> form的validateFields支持promise用法

src/createBaseForm.js, src/createFieldsStore.js, tests/dynamic-rule.spec.js, tests/validateFields.spec.js
ref:  https://github.com/ant-design/ant-design/issues/13689
This may no need use set `force` in validate anymore.
=> reset fields dirty for re-check

src/createBaseForm.js
'!==' will invoke a bug when occurred with NaN.
=> modify compare logic when validating

src/createBaseForm.js, tests/validateArray.spec.js
fix https://github.com/ant-design/ant-design/issues/14275
Add additional check logic. Little tricky. Pls help to check on this.
=> support array type validate

src/createBaseForm.js, tests/getFieldDecorator.spec.js
Fixes https://github.com/ant-design/ant-design/issues/12960
=> fix: Show warning when user assigns same name to 2 or more fields.

src/createBaseForm.js, tests/async-validation.spec.js, tests/validateFieldsAndScroll.spec.js
Related
https://github.com/ant-design/ant-design/issues/5590
=> fix: validateFields function not resolve or reject

package.json, src/createBaseForm.js
close #330
close #163
ref ant-design/ant-design#9792
https://github.com/react-component/util/commit/96a992414eba8fcf1a30dbea8118a82610f88994
=> ⚠️ fix unsafe lifecycle warnings
